module.exports = {
  _id: 'careersPage-singleton',
  _type: 'careersPage',
  hero: {
    eyebrow: 'Careers',
    headline: "Build the world's most complex projects. From the owner's side.",
    body: "Praetorian offers career opportunities in project management with a primary focus on capital project development in the mining industry. Successful candidates demonstrate an interest and personal drive towards growth in their leadership and technical abilities.",
    primaryCtaLabel: 'View Opportunities',
    secondaryCtaLabel: 'Submit a Profile',
  },
  whyChooseUs: {
    eyebrow: 'Why Choose Us',
    heading: 'Our people are our delivery capability',
    paragraphs: [
      'Our core training and development programs support the principle of mentoring through developmental delegation. This ensures a system of successor preparation and cross support of responsibilities for each position on a project team.',
      'Team leaders are challenged to position their teams to optimise skills and abilities while setting individual growth goals for each project member. Our teams consist of Engineers, Technologists, and Tradespersons, providing a balanced approach to managing projects and the contractors who deliver them.',
      'Recognising the value of the balance between profession and family, Praetorian has a high focus on quality of life promoted through optimised project shift schedules, team development retreats, sporting activities, and milestone celebrations where family participation is encouraged.',
    ],
    benefits: [
      {
        _key: 'k1',
        _type: 'benefit',
        title: 'Global project exposure',
        description: 'Operations in Canada, the USA, South America, Central America, and Eurasia. Our people work on projects that few firms in the world have access to.',
      },
      {
        _key: 'k2',
        _type: 'benefit',
        title: "Owner's team accountability",
        description: "Embedded directly in the client's ownership team, making decisions that directly affect project outcomes.",
      },
      {
        _key: 'k3',
        _type: 'benefit',
        title: 'People-first culture',
        description: 'Training programs in leadership, management systems, and technical subjects. Internal recognition, family-inclusive milestones, and a lower-than-average employee turnover rate.',
      },
      {
        _key: 'k4',
        _type: 'benefit',
        title: 'Technology-forward culture',
        description: 'Praetorian is investing in AI-powered project intelligence through Praetorian IQ, reshaping how mining construction is managed globally.',
      },
    ],
  },
  peopleSection: {
    eyebrow: 'Our People, Our Value',
    quote: 'I have been working with Praetorian for 7 years as Human Resource Manager and my favourite part about the company is the diverse work experience and locations, the international work and how much I am involved as a whole with the day to day operations. Working at Praetorian, the day to day direct contact with all members of the Team provides that “home” and “human” element to an industry that is sometimes lost with a larger organisation. Praetorian’s employee turnover rate is lower and they take care of their Team! Calling for all talents, the opportunities are endless and the next exciting opportunity is just around the corner!',
    authorInitials: 'AG',
    authorName: 'Annette Genge',
    authorTitle: 'Human Resource Manager',
    ctaLabel: 'Apply Now',
    stat1Value: '7+',
    stat1Label: 'Years average tenure for senior staff',
    stat2Value: '6',
    stat2Label: 'Countries with active project deployments',
    stat3Title: 'Equal opportunity employer',
    stat3Body: 'We do not discriminate on the basis of race, gender, age, religion, disability, or sexual orientation',
  },
  disciplinesSection: {
    eyebrow: 'Disciplines we hire',
    heading: 'What we look for',
    disciplines: [
      {
        _key: 'k1',
        _type: 'discipline',
        title: 'Project Controls',
        description: 'Cost engineers, schedulers, estimators, and document controllers with mining or heavy industrial project experience.',
        tags: 'P6 · Prism · ACCE · Excel',
      },
      {
        _key: 'k2',
        _type: 'discipline',
        title: 'Construction Management',
        description: 'Field-experienced construction managers, superintendent-level personnel, and quality leads who have run contractor teams on complex builds.',
        tags: 'Open pit · Process plant · Infrastructure',
      },
      {
        _key: 'k3',
        _type: 'discipline',
        title: 'Engineering Support',
        description: 'Engineers with constructability review and value engineering backgrounds, able to interrogate contractor designs on behalf of the owner.',
        tags: 'Civil · Structural · Process · Mechanical',
      },
      {
        _key: 'k4',
        _type: 'discipline',
        title: 'Procurement and Contracts',
        description: 'Contracts administrators and procurement specialists with experience managing major vendor packages and subcontract performance.',
        tags: 'FIDIC · NEC · Lump sum · EPCM',
      },
      {
        _key: 'k5',
        _type: 'discipline',
        title: 'HSSE Leadership',
        description: 'Health, safety, and environmental professionals who lead from the field, experienced in remote, high-hazard mining and heavy construction environments.',
        tags: 'CRSP · NEBOSH · ISO 14001',
      },
      {
        _key: 'k6',
        _type: 'discipline',
        title: 'Commissioning and Turnover',
        description: 'Commissioning managers and QA/QC leads experienced in punch list closure, system handover packages, and ramp-up performance management.',
        tags: 'Mechanical · Electrical · Instrumentation',
      },
    ],
  },
  opportunities: {
    eyebrow: 'Employment Opportunities',
    heading: 'Live Positions',
    paragraph1: "Thank you for considering employment with Praetorian. Specific openings are posted as engagements are confirmed. If you don't see a role that matches your background, send us a profile; we maintain a register of qualified candidates for upcoming projects.",
    paragraph2Prefix: 'Send your resume directly to:',
    contactCtaLabel: 'Contact Careers',
    stayConnectedLabel: 'Stay Connected',
    linkedinLabel: 'Follow us on LinkedIn for future opportunities',
    currentOpeningsLabel: 'Current Openings',
    openings: [
      { _key: 'k1', _type: 'opening', title: 'Senior Cost Engineer', meta: 'Location TBC · Project-based engagement' },
      { _key: 'k2', _type: 'opening', title: 'Construction Manager', meta: 'Location TBC · Project-based engagement' },
      { _key: 'k3', _type: 'opening', title: 'Project Controls Lead', meta: 'Location TBC · Project-based engagement' },
    ],
    careerOpportunitiesLabel: 'Career Opportunities Include',
    roles: [
      'Project Managers',
      'Contracts Managers',
      'Construction Managers',
      'Safety Professionals',
      'Project Engineers',
      'IT Specialists',
      'Business Managers',
      'Survey and CAD Managers',
      'Superintendents',
      'Procurement Specialists',
      'Cost Controllers',
      'Warehouse and Inventory',
      'Planners and Schedulers',
      'Quality Assurance Managers',
      'Field Engineers',
      'QC Inspectors',
      'Commissioning Supts.',
      'Administration Personnel',
      'Document Controllers',
      'Logistics Specialists',
    ],
    disclaimerNote: 'Live job listings will be CMS-driven at launch. Placeholder roles shown for layout review.',
  },
};
