module.exports = {
  _id: 'privacyPage-singleton',
  _type: 'privacyPage',
  title: 'Privacy Policy',
  lastUpdated: 'September 2026',
  body: [
    { _key: 'k1', _type: 'block', style: 'h2', children: [{ _key: 'k1c1', _type: 'span', text: 'Who We Are', marks: [] }], markDefs: [] },
    { _key: 'k2', _type: 'block', style: 'normal', children: [{ _key: 'k2c1', _type: 'span', text: 'Praetorian is an industrial project management and construction management firm headquartered in Edmonton, Alberta, Canada. Our website is located at praetoriancm.com.', marks: [] }], markDefs: [] },
    { _key: 'k3', _type: 'block', style: 'normal', children: [{ _key: 'k3c1', _type: 'span', text: 'This policy applies to the following entities operating under the Praetorian Group of Companies:', marks: [] }], markDefs: [] },
    { _key: 'k4', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k4c1', _type: 'span', text: 'Praetorian Construction Management Ltd.', marks: [] }], markDefs: [] },
    { _key: 'k5', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k5c1', _type: 'span', text: 'Praetorian Construction Management International Ltd.', marks: [] }], markDefs: [] },
    { _key: 'k6', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k6c1', _type: 'span', text: 'Praetorian Legate Corporation.', marks: [] }], markDefs: [] },
    { _key: 'k7', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k7c1', _type: 'span', text: 'PCMI US Inc.', marks: [] }], markDefs: [] },
    { _key: 'k8', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k8c1', _type: 'span', text: 'PCMI-México S. DE R.L. DE C.V.', marks: [] }], markDefs: [] },
    { _key: 'k9', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k9c1', _type: 'span', text: 'PCMI-Peru S.A.C.', marks: [] }], markDefs: [] },
    { _key: 'k10', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k10c1', _type: 'span', text: 'Eurasia Project Management Services Inc.', marks: [] }], markDefs: [] },
    { _key: 'k11', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k11c1', _type: 'span', text: 'Optios Properties Ltd.', marks: [] }], markDefs: [] },
    { _key: 'k12', _type: 'block', style: 'normal', listItem: 'number', level: 1, children: [{ _key: 'k12c1', _type: 'span', text: 'Scuta Project Management Limited.', marks: [] }], markDefs: [] },
    { _key: 'k13', _type: 'block', style: 'h2', children: [{ _key: 'k13c1', _type: 'span', text: 'What Information We Collect', marks: [] }], markDefs: [] },
    { _key: 'k14', _type: 'block', style: 'normal', children: [{ _key: 'k14c1', _type: 'span', text: 'We collect information in two ways:', marks: [] }], markDefs: [] },
    {
      _key: 'k15',
      _type: 'block',
      style: 'normal',
      markDefs: [],
      children: [
        { _key: 'k15c1', _type: 'span', text: 'Information you provide directly.', marks: ['strong'] },
        { _key: 'k15c2', _type: 'span', text: ' When you submit our contact form, we collect your name, email address, company name, and the message you send. We do not collect payment information through our website.', marks: [] },
      ],
    },
    {
      _key: 'k16',
      _type: 'block',
      style: 'normal',
      markDefs: [],
      children: [
        { _key: 'k16c1', _type: 'span', text: 'Information collected automatically.', marks: ['strong'] },
        { _key: 'k16c2', _type: 'span', text: ' When you visit our website, we collect standard analytics data through Google Analytics 4, including pages visited, time spent on the site, general geographic location (city and country level), and device type. This data is aggregated and does not identify you personally.', marks: [] },
      ],
    },
    { _key: 'k17', _type: 'block', style: 'h2', children: [{ _key: 'k17c1', _type: 'span', text: 'How We Use Your Information', marks: [] }], markDefs: [] },
    { _key: 'k18', _type: 'block', style: 'normal', children: [{ _key: 'k18c1', _type: 'span', text: 'We use the information you provide to:', marks: [] }], markDefs: [] },
    { _key: 'k19', _type: 'block', style: 'normal', listItem: 'bullet', level: 1, children: [{ _key: 'k19c1', _type: 'span', text: 'Respond to your enquiry or request', marks: [] }], markDefs: [] },
    { _key: 'k20', _type: 'block', style: 'normal', listItem: 'bullet', level: 1, children: [{ _key: 'k20c1', _type: 'span', text: 'Follow up on business development conversations', marks: [] }], markDefs: [] },
    { _key: 'k21', _type: 'block', style: 'normal', listItem: 'bullet', level: 1, children: [{ _key: 'k21c1', _type: 'span', text: 'Send information about our services if you have requested it', marks: [] }], markDefs: [] },
    { _key: 'k22', _type: 'block', style: 'normal', children: [{ _key: 'k22c1', _type: 'span', text: 'We use analytics data to understand how visitors use our website and to improve its content and performance.', marks: [] }], markDefs: [] },
    { _key: 'k23', _type: 'block', style: 'normal', children: [{ _key: 'k23c1', _type: 'span', text: 'We do not sell your personal information.', marks: [] }], markDefs: [] },
    { _key: 'k24', _type: 'block', style: 'normal', children: [{ _key: 'k24c1', _type: 'span', text: 'We do not share your information with third parties except as described below.', marks: [] }], markDefs: [] },
    { _key: 'k25', _type: 'block', style: 'h2', children: [{ _key: 'k25c1', _type: 'span', text: 'Third-Party Services', marks: [] }], markDefs: [] },
    { _key: 'k26', _type: 'block', style: 'normal', children: [{ _key: 'k26c1', _type: 'span', text: 'Our website uses the following third-party services:', marks: [] }], markDefs: [] },
    {
      _key: 'k27',
      _type: 'block',
      style: 'normal',
      listItem: 'bullet',
      level: 1,
      markDefs: [],
      children: [
        { _key: 'k27c1', _type: 'span', text: 'Google Analytics 4', marks: ['strong'] },
        { _key: 'k27c2', _type: 'span', text: " for website traffic and behaviour analysis. Google's privacy policy applies to data processed through this service.", marks: [] },
      ],
    },
    {
      _key: 'k28',
      _type: 'block',
      style: 'normal',
      listItem: 'bullet',
      level: 1,
      markDefs: [],
      children: [
        { _key: 'k28c1', _type: 'span', text: 'Resend', marks: ['strong'] },
        { _key: 'k28c2', _type: 'span', text: ' to deliver contact form submissions to our team. Messages are transmitted securely and not stored beyond what is needed to process your enquiry.', marks: [] },
      ],
    },
    { _key: 'k29', _type: 'block', style: 'h2', children: [{ _key: 'k29c1', _type: 'span', text: 'Data Retention', marks: [] }], markDefs: [] },
    { _key: 'k30', _type: 'block', style: 'normal', children: [{ _key: 'k30c1', _type: 'span', text: 'Contact form enquiries are retained for as long as necessary to respond to your request and for reasonable follow-up thereafter.', marks: [] }], markDefs: [] },
    { _key: 'k31', _type: 'block', style: 'normal', children: [{ _key: 'k31c1', _type: 'span', text: 'Analytics data is retained in accordance with Google Analytics default settings (14 months).', marks: [] }], markDefs: [] },
    { _key: 'k32', _type: 'block', style: 'h2', children: [{ _key: 'k32c1', _type: 'span', text: 'Your Rights', marks: [] }], markDefs: [] },
    { _key: 'k33', _type: 'block', style: 'normal', children: [{ _key: 'k33c1', _type: 'span', text: 'If you are located in Canada, you have rights under the Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable provincial legislation. You may request access to, correction of, or deletion of your personal information by contacting us at the address below.', marks: [] }], markDefs: [] },
    { _key: 'k34', _type: 'block', style: 'normal', children: [{ _key: 'k34c1', _type: 'span', text: 'If you are located in the European Economic Area, you have rights under the General Data Protection Regulation (GDPR), including the right to access, correct, and request deletion of your personal data.', marks: [] }], markDefs: [] },
    { _key: 'k35', _type: 'block', style: 'h2', children: [{ _key: 'k35c1', _type: 'span', text: 'Cookies', marks: [] }], markDefs: [] },
    { _key: 'k36', _type: 'block', style: 'normal', children: [{ _key: 'k36c1', _type: 'span', text: 'Our website uses cookies to support analytics functionality. You can control cookie settings through your browser. Disabling cookies may affect the functionality of some parts of the site.', marks: [] }], markDefs: [] },
    { _key: 'k37', _type: 'block', style: 'h2', children: [{ _key: 'k37c1', _type: 'span', text: 'Contact', marks: [] }], markDefs: [] },
    { _key: 'k38', _type: 'block', style: 'normal', children: [{ _key: 'k38c1', _type: 'span', text: 'For any privacy-related questions or requests, please contact:', marks: [] }], markDefs: [] },
    {
      _key: 'k39',
      _type: 'block',
      style: 'blockquote',
      markDefs: [
        { _key: 'k39mEmail', _type: 'link', href: 'mailto:info@praetoriancm.com' },
        { _key: 'k39mPhone', _type: 'link', href: 'tel:7809890289' },
      ],
      children: [
        { _key: 'k39c1', _type: 'span', text: 'Praetorian Construction Management Ltd.\n', marks: ['strong'] },
        { _key: 'k39c2', _type: 'span', text: '201, 10441-178 Street\nEdmonton, Alberta, T5S 1R5, Canada\n', marks: [] },
        { _key: 'k39c3', _type: 'span', text: 'info@praetoriancm.com', marks: ['k39mEmail'] },
        { _key: 'k39c4', _type: 'span', text: '\n', marks: [] },
        { _key: 'k39c5', _type: 'span', text: '(780) 989-0289', marks: ['k39mPhone'] },
      ],
    },
    { _key: 'k40', _type: 'block', style: 'h2', children: [{ _key: 'k40c1', _type: 'span', text: 'Changes to This Policy', marks: [] }], markDefs: [] },
    { _key: 'k41', _type: 'block', style: 'normal', children: [{ _key: 'k41c1', _type: 'span', text: 'We may update this policy from time to time. The date at the top of this page reflects the most recent revision. Continued use of the website after any update constitutes acceptance of the revised policy.', marks: [] }], markDefs: [] },
  ],
};
