module.exports = [
  {
    _id: 'project-amulsar',
    _type: 'project',
    title: 'Lydian International – Amulsar Gold Project',
    slug: { _type: 'slug', current: 'amulsar' },
    client: 'Lydian International',
    location: 'Vayots Dzor, Armenia',
    year: '2015 – 2018',
    phase: 'Flagship',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/08/Amulsar.jpg',
    excerpt: 'Amulsar Gold Project is a greenfield 225,000 gold ounces per annum mine in the Republic of Armenia. Praetorian provided supports ranging from feasibility review, assistance in preparation for financing, environmental and social impact assessment review, project management, construction management and precommissioning.',
    overviewParagraphs: [
      "Amulsar Gold Project is a greenfield 225,000 gold ounces per annum mine in the Republic of Armenia. Praetorian provided supports ranging from feasibility review, assistance in preparation for financing, environmental and social impact assessment review, project management, construction management and precommissioning.",
      "Praetorian's unique skillsets were critical to the success of this project, including remote region construction expertise, experience with constructability reviews to capture cost savings, engineering interface for seamless integration with construction, construction driven-approach, early identification of contractor strengths and ability to breach gaps identified to ensure project success, staffing with Praetorian personnel with multidiscipline skillsets.",
    ],
    secondaryListLabel: 'Facilities',
    secondaryListItems: [
      'Crusher Facility and Adsorption, Desorption and Recovery (ADR) Facility',
      'Heap Leach Facility (Ponds, Dams, Channels)',
      'Screening Facility, Water Channels, Ponds and Dams',
      'Explosive Storage and Accommodation Camps',
      'Conveyor Systems and Barren Rock Storage Facility',
      'Mine Shop and Related Facilities',
      'Site Services and Utilities (Water, Gas, Power) and Haul Roads',
    ],
    scope: 'Feasibility Review and Input for Project Development, Support for Financing, Support for ESIA, Development, Value Engineering, Procurement, Contracts Development and Administration, Cost Control, Scheduling, Constructability, Survey Data Management, Survey, Overall Project Management, Construction Management, Pre-commissioning and Operations Preparations Support.',
    featured: true,
    order: 1,
  },
  {
    _id: 'project-conga',
    _type: 'project',
    title: 'Newmont Mining Corp – Conga Mine',
    slug: { _type: 'slug', current: 'conga' },
    client: 'Newmont (Yanacocha – MYSRL)',
    location: 'Cajamarca, Peru',
    year: '2010 – 2014',
    phase: 'Execution',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/08/BannerConga.jpg',
    excerpt: 'The Conga project is an open pit copper/gold mine covering approx. 6,000 ha in a remote area of the Peruvian Andes. The project involves a substantial amount of earthworks infrastructure with significant water management requirements.',
    overviewParagraphs: [
      'The Conga project is an open pit copper/gold mine. The project covers a vast area of approx. 6,000 ha and involves a substantial amount of earthworks infrastructure in a remote area of the Peruvian Andes. The average elevation is approximately 3,800 m and there is significant water management required during the wet season where annual rainfalls can exceed 1.2m.',
      'Praetorian provided survey data and Cadd Modelling management, collating data from multiple survey groups, overall site map information management, as-builts, quantity and quality control for contractor payment, and aggregate quantity management.',
    ],
    secondaryListLabel: 'Key Quantities',
    secondaryListItems: [
      '20 water storage dams, tailings dams, and sediment ponds',
      '25 km of water diversion channels',
      '70 km of permanent and temporary roads',
      '25M m3 of contractor excavated earthworks',
      '10M m3 of Mine Operations supplied rock fill for earthworks structures',
    ],
    scope: 'Earthworks Project and Construction Management, Value Engineering and Constructability, Survey Data Control and Cadd Modeling Management.',
    featured: true,
    order: 2,
  },
  {
    _id: 'project-penasquito',
    _type: 'project',
    title: 'Goldcorp Inc. – Peñasquito Mine CLR Project',
    slug: { _type: 'slug', current: 'penasquito' },
    client: 'Goldcorp Inc.',
    location: 'Zacatecas, Mexico',
    year: '2016 – 2019',
    phase: 'Execution',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/09/Penasquito.jpg',
    excerpt: 'Goldcorp’s Peñasquito Mine CLR (Centerline Raise) project is a brownfield expansion of the tailings facility and tailings systems involving the construction of lined tailings dams, reclaim ponds, access roads and tailings pumping systems.',
    overviewParagraphs: [
      "Goldcorp's Peñasquito Mine CLR (Centerline Raise) project is a brownfield expansion of the tailings facility and tailings systems. The project involves the construction of lined tailings dams, reclaim ponds, access roads, tailings pumping systems, tailings discharge and water reclaim systems for the purpose of increasing the overall capacity of the tailings storage facility.",
      "Praetorian provided Project Management services by integrating with the Goldcorp personnel as part of the owners' team, including training of Goldcorp staff for future tailings facility raises and heavy equipment operator training of local residents.",
    ],
    secondaryListLabel: 'Key Quantities',
    secondaryListItems: [
      '20M m3 Bulk Excavation',
      '13M m3 Bulk Mine Waste Rock Fill',
      '790,000 m2 of geomembrane liner',
      '15 km of LB Pipe',
      '8.3 km of cable and 28 large diameter pumps',
      '220 person camp expansion',
    ],
    scope: 'Project Management, Construction Management, Cost Control, Scheduling, Constructability, and CM Team Training.',
    featured: true,
    order: 3,
  },
  {
    _id: 'project-emigrant',
    _type: 'project',
    title: 'Newmont Mining Corp – Emigrant Mine',
    slug: { _type: 'slug', current: 'emigrant' },
    client: 'Newmont Mining Corp',
    location: 'Carlin, Nevada, USA',
    year: '2011 – 2012',
    phase: 'Commissioned',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/08/Emigrant-Aerial.jpg',
    excerpt: 'Newmont’s Emigrant Mine is a greenfield mine development near Carlin, Nevada. The project involves the construction of access roads, a leach pad, water management facilities, a carbon in column processing plant, and related infrastructure.',
    overviewParagraphs: [
      "Newmont's Emigrant Mine is a greenfield mine development near Carlin, Nevada. The project involves the construction of access roads, a leach pad, water management facilities, a carbon in column processing plant, and related infrastructure.",
      "Praetorian provided overall Project Management services by integrating with Newmont personnel as part of the owners' team. Responsibilities included feasibility support, management of engineering firms, constructability planning, equipment installation sequencing and feedback to designers to reduce construction costs.",
    ],
    secondaryListLabel: 'Key Quantities',
    secondaryListItems: [
      '80 acre leach pad',
      '500,000 m2 of geomembrane liner',
      '53 km of HDPE and carbon steel pipelines',
      '3,000,000 m3 of material placed for roads, dams and leach pads',
      'New CIC process plant, fuel island, lube storage building, wash bay and truck shop expansion',
    ],
    scope: 'Project Management, Construction Management, Cost Control, Scheduling, Constructability.',
    featured: true,
    order: 4,
  },
  {
    _id: 'project-diavik',
    _type: 'project',
    title: 'Diavik Diamond Mines Inc. – Diavik Underground Project',
    slug: { _type: 'slug', current: 'diavik' },
    client: 'Diavik Diamond Mines Ltd.',
    location: 'Lac De Gras, NWT, Canada',
    year: '2006 – 2013',
    phase: 'Operations',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/08/Diavik.jpg',
    excerpt: 'Diavik’s Underground Project covers work associated with the transition from an open pit to underground operation. Praetorian’s cold weather (arctic) construction expertise and detailed logistics support were critical to the success of this project.',
    overviewParagraphs: [
      "Diavik's Underground Project is the overall project title for work associated with the transition from an open pit to underground operation. There are numerous sub-projects within this major expansion. Several of Praetorian's key differentiators were critical to the success of this project, including cold weather (arctic) construction expertise and detailed materials and construction equipment logistic support due to ice road constraints.",
      "Praetorian provided Survey Data Control, Cadd Modeling and Site Mapping including earthwork layout and planning for contractor and client forces, survey data and Cadd Modelling management, collating data from multiple survey groups, overall site map information management, as-builts, quantity and quality control for contractor payment, and aggregate quantity management.",
    ],
    secondaryListLabel: 'Sub-Projects',
    secondaryListItems: [
      'PKC (tailings) dam raises (4 ea @ 5m per)',
      'Power generation expansion (additional 25 MW)',
      'Water treatment expansion (45,000 m3/day)',
      'Aggregate production facility (600 T/hr)',
      'Cemented backfill facility including 5m ball mill and thickener',
      'Additional 54M litres of diesel storage',
      '240 room accommodation expansion and 700 room renovation',
      'Underground dewatering stations and maintenance shop',
      'Management of over 12M m3 of earthworks movement',
    ],
    scope: 'Project Management, Construction Management, Cost Control, Scheduling, Constructability, Survey Data Management, Survey.',
    featured: true,
    order: 5,
  },
  {
    _id: 'project-so2clean',
    _type: 'project',
    title: 'Calabrian Corporation – SO2Clean Production Facility',
    slug: { _type: 'slug', current: 'so2clean' },
    client: 'Calabrian Corporation',
    location: 'Porcupine, Ontario, Canada',
    year: '2015 – 2017',
    phase: 'Commissioned',
    photoUrl: 'https://www.praetoriancm.com/wp-content/uploads/2018/08/Calabrian-Plant-1.jpg',
    excerpt: 'Calabrian’s SO2Clean Production Facility is a 100 TPD Liquid Sulphur Dioxide Production Plant in Northern Ontario, Canada. Praetorian was responsible for overall Project Management and Construction Management.',
    overviewParagraphs: [
      "Calabrian's SO2Clean Production Facility Project is a 100 TPD Liquid Sulphur Dioxide Production Plant in Northern Ontario, Canada. Praetorian was responsible for overall Project Management and Construction Management. Praetorian's overall project management expertise including experience in remote locations construction and engineering/procurement/construction interface management was critical to the success of this project.",
      "Praetorian met with various local contractors to identify local skillset, made recommendations to client on community engagement, and proactively managed local community's expectations throughout the project lifecycle.",
    ],
    secondaryListLabel: 'Services Delivered',
    secondaryListItems: [
      'Feasibility data review and validation (budget and schedule)',
      'Value engineering and constructability',
      'Civil, earthworks and full multi-discipline construction management',
      'Project controls (WBS, CBS, Primavera P6 scheduling, Prism G2 cost control)',
      'Contractor prequalification, RFP development and contract administration',
      'Community relations and local contractor engagement',
    ],
    scope: 'Project Management, Construction Management, Cost Control, Scheduling, Constructability.',
    featured: true,
    order: 6,
  },
];
